name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

env:
  NUGET_SOURCE: "https://api.nuget.org/v3/index.json"

jobs:
  build-test:
    name: Client (${{ matrix.dotnet-target-framework }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-target-framework: ["net6.0", "net7.0"]
        include:
          - dotnet-install-framework: 6.0.x
            dotnet-target-framework: net6.0
          - dotnet-install-framework: 7.0.x
            dotnet-target-framework: net7.0
    env:
      source-directory: ./src
      source-project: ExceptionsAPI.csproj
      test-directory: ./test
      test-project: ExceptionsAPI.Test.csproj

    steps:
      - uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-install-framework }}
          include-prerelease: true

      - name: Install Dependencies
        run: |
          dotnet restore ${{ env.source-directory }}/${{ env.source-project }} -p:TargetFramework=${{ matrix.dotnet-target-framework }}
          dotnet restore ${{ env.test-directory }}/${{ env.test-project }} -p:TargetFramework=${{ matrix.dotnet-target-framework }}

      - name: Build
        working-directory: ${{ env.source-directory }}
        run: dotnet build --configuration Release -p:TargetFramework=${{ matrix.dotnet-target-framework }} --no-restore

      - name: Test
        working-directory: ${{ env.test-directory }}
        run: dotnet test -p:TargetFramework=${{ matrix.dotnet-target-framework }} --no-restore --verbosity normal

  release:
    name: Publish Release
    needs: [build-test]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    env:
      project-path: ./ExceptionsAPI.csproj
      release-path: ./bin/Release

    steps:
      - uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
          include-prerelease: true

      - name: Install Dependencies
        working-directory: ./src
        run: |
          dotnet restore ${{ env.project-path }}

      - name: Create Release Packages
        working-directory: ./src
        run: |
          dotnet pack ${{ env.project-path }} -c Release --no-restore -p:PackageVersion=${{ github.event.release.tag_name }}

      - name: Push Release Packages
        working-directory: ./src
        run: |
          dotnet nuget push ${{ env.release-path }}/ExceptionsAPI.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ env.NUGET_SOURCE }}
